services:
  - type: web
    name: food-expiry-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_sqlite:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
